<?php

namespace Database\Seeders;

use App\Models\Testimonial;
use Illuminate\Database\Seeder;

class TestimonialSeeder extends Seeder
{
    public function run(): void
    {
        $testimonials = [
            ['name' => 'Mr. Alagappan Ramiya', 'company' => 'Toyota Lifts India Pvt. Ltd.', 'designation' => '', 'excerpt' => 'Taxlegal has provided reliable tax advice and excellent service for over five years. Their expertise has made taxation much simpler, and I highly recommend them.', 'testimonial' => 'Taxlegal has provided me with sound advice and fine service for the last 5 years that I have used them and I continue to use them. My taxation has been made much simpler through your efforts. I would highly recommend your firm to any person who requires taxation related services.'],
            ['name' => 'Mr. Ishwar Mistry', 'company' => 'Vivin Kraft Pvt. Ltd.', 'designation' => '', 'excerpt' => 'For nearly 15 years, Taxlegal has been our trusted advisor, helping us with tax planning, strategy, and consistent professional support.', 'testimonial' => 'TaxLegal has been our consultant partners for almost 15 years as of now, we have found an incredible support from them, its just not all about filling of the IT returns or any taxation, but its more about planning, strategising from day one. The team is very professional, prompt in their service, consistent followups. The documents are well organisised. For a person like me who is not very process oriented have understood the value and importants for maintaining these records. As Taxlegal Team truly says, they believe in "Beyond Bottom Line", they walk the talk and have been our great pillar support.'],
            ['name' => 'Mr. Tanvir Oberoi', 'company' => 'VIG Auto Accessories', 'designation' => 'Proprietor', 'excerpt' => 'Taxlegal resolved our tax issues, strengthened our financial practices, and became a trusted partner in our company\'s growth.', 'testimonial' => 'Besides being extremely competent and knowledgeable, Mr. Sharma at TaxLegal had helped me straighten out my previous tax issues and had advised me on the best taxation practices to manage my business as well as personal taxes. Also, the TaxLegal team is very helpful, responsive, and very communicative. They were able to catch and correct all my prior taxation mistakes. I definitely recommend TaxLegal & their accounting team, to anyone that is looking for responsible accounts and tax consultant, who can get things done in a proper way. Over these years, their best practices have really helped my automotive parts company to grow and achieve financial well-being. I can\'t thank them enough. Strong roots produce beautiful leaves - this is how the Taxlegal team has helped us, by strengthening our foundations, our roots in accounting, taxation and financial aspects.'],
            ['name' => 'Mr. M. M. Khan', 'company' => 'Dhanlaxmi Electricals Pvt. Ltd.', 'designation' => 'Managing Director', 'excerpt' => 'Professional, knowledgeable, and dependable guidance helped us overcome complex multi-state taxation challenges.', 'testimonial' => 'Mr. Suresh Sharma and the entire Tax Legal team are very efficient, polite and knowledgeable. He been very helpful and professional and have been providing effective advice to us to resolve our tax issues. Adv.Sharma is an intelligent and thoughtful tax adviser. He been very helpful and professional and have been providing effective advice to us to resolve our tax issues. He has been highly helpful to us, when we were struggling with various states taxation compliances for our company. He is very patient and considerate in understanding our queries as well as responsive in answering our questions. We are most pleased with Mr. Sharma\'s professional assistance, as well as the assistance of his associates at Taxlegal.'],
            ['name' => 'Nitish Bhattacharjee', 'company' => 'Pronnoy Fine Arts', 'designation' => '', 'excerpt' => 'A trusted advisor whose problem-solving skills, patience, and thoughtful guidance have stood the test of time.', 'testimonial' => 'I do remember meeting Mr. Sharma almost sixteen years back. All I remember is I did found a thorough gentleman, a great friend who was extremely good at listening, patiently enough, paying attention to every tiny details in depth, coming up with new ideas for very - complex situations. Someone who understands, communicates and knows his craft at best. The very precise element I personally would look in him is his problem solving abilities, makes him stand apart from rest. I find myself at the luxury to communicate at any hour of the day. I wish him and his team a great success.'],
            ['name' => 'Mr. Aman Saxena', 'company' => 'Identify Architect', 'designation' => '', 'excerpt' => 'Taxlegal\'s expertise gives us complete confidence in handling complex accounting and taxation compliance.', 'testimonial' => 'Adv Suresh has the ability and knowledge to address very complex issues related to accounting, taxation compliances. To my knowledge, he has a detailed and vast experience in tax law that allow his clients to achieve and maintain full compliance with reasonable efforts. Now I can feel relieved knowing we are in the best hands to prepare our returns and sort all situations. Net, we are very satisfied with Taxlegal services'],
            ['name' => 'Mr. Swapneel Dange', 'company' => 'The Dange Company', 'designation' => '', 'excerpt' => 'More than a tax consultant, Mr. Sharma became a mentor who guided our business growth through practical advice.', 'testimonial' => 'I met my Tax Attorney Mr. Suresh Sharma in the year 2011 when I have moved back from US to India. Initial assignment was to help me become aware of the Indian Tax environment and its laws, but his help was so immense that I ended up consulting him on everything such as business growth, employee hiring, sales target revisions, etc. His inherent quality is \'Never say NO\' attitude. No matter how complex the task at hand looks, he always gets it done, via meticulous planning and staged execution. He taught me the keyword \'Baby Steps\'. He says irrespective of the difficult nature of any project, it can be completed easily if the project is executed in continuous smaller steps (Baby steps). His other quality that really sticks with me, is his continuous learning. Routinely he keeps himself abreast with the changing landscape in the tax environment of a specific business segment or of a specific region or of a specific country. I would summarize to say that he has been a true professional and a great mentor, who is available beck and call.'],
            ['name' => 'Rohit Mhapralkar', 'company' => 'Fitness Freak', 'designation' => '', 'excerpt' => 'Professional service, excellent communication, and personalized financial planning exceeded our expectations.', 'testimonial' => 'Thorough, Professional and Excellent service. Taxlegal - their communication was amazing, and I really appreciated the one-on-one review on the financial, accounting and taxation planning. Everything was convenient, and they worked around my schedule. They are approachable, easy to contact and got back to me quickly. I was very happy with the results, service, and cost. I highly recommend them.'],
            ['name' => 'CGS Manish', 'company' => '', 'designation' => '', 'excerpt' => 'Excellent professional service, prompt responses, and dedicated client support make Taxlegal a firm I would confidently recommend.', 'testimonial' => 'Excellent professional service to clients. Speed in response on queries as also good hand holding of the clients. Professional, helpful and very competent. I would not hesitate in recommending them.'],
            ['name' => 'Sushil Sharma', 'company' => '', 'designation' => '', 'excerpt' => 'Our family has greatly benefited from Taxlegal\'s timely reminders, professional guidance, and prompt resolution of tax and GST matters.', 'testimonial' => 'I really appreciate how Suresh ji and his team has helped us (3 of us in family) to comply with Tax requirements of Govt Of India in timely manner with prompt prior reminders and resolving disputes if any be it be related to personal Tax or GST matters. Thanking tax legal team ones again.'],
            ['name' => 'Kuldeep Singh', 'company' => '', 'designation' => '', 'excerpt' => 'Long-term association and highly reliable support for accounting, tax, and GST matters.', 'testimonial' => 'I have been using their services for last 15 Years. They have been very supportive when it comes to handle your problems. Their staff is professional and with high skill levels. I will always recommend to avail their services, in case anyone need.'],
            ['name' => 'Mitesh Shah', 'company' => '', 'designation' => '', 'excerpt' => 'With over 15 years of reliable service, Taxlegal\'s experienced team has always provided professional support and effective solutions.', 'testimonial' => 'I have been associated with Taxlegal for the past 12 years and during this period, I must say that the entire team led by Adv. Suresh Sharma have been doing a great job for my companies. They handle all the compliances including Income Tax, GST, ROC, etc. without any issues. Whenever we require any clarification or guidance on tax and regulatory matters, they always respond very quickly and provide the best solution. Their team is very professional and dedicated to their work. Keep up the good work Taxlegal Team.'],
            ['name' => 'Arvind Singh', 'company' => '', 'designation' => '', 'excerpt' => 'I found Sharma & company best in business of legal and tax matters. Most supportive and cooperative team of hard working and dedicated staff.', 'testimonial' => 'I found Sharma & company best in business of legal and tax matters. Most supportive and cooperative team of hard working and dedicated staff always ready to address my concerns... all the best'],
            ['name' => 'Mr. Arjoon Nangia', 'company' => 'MDS CO', 'designation' => '', 'excerpt' => 'Accurate, clear, quick and reliable. Adv Suresh Sharma is an intelligent and thoughtful tax adviser who takes care of every detail.', 'testimonial' => 'Accurate, clear, quick and reliable To help us get the most for the business, they are always there to take care of every nitty gritty which needs at attention. Adv Suresh Sharma is an intelligent and thoughtful tax adviser . We are most pleased with Adv. Suresh Sharma\'s professional assistance, as well as the assistance of his associates at Taxlegal.'],
            ['name' => 'Mr. Anuj Mehta', 'company' => 'Sai Auto Accessories', 'designation' => '', 'excerpt' => 'Responsive, Client Oriented, Expert Tax Consultant. I received very personalized and thorough service related to tax planning, filing and other compliances.', 'testimonial' => 'Responsive, Client Oriented, Expert Tax Consultant. I received very personalized and thorough service related to tax planning, filling and other complainces.'],
            ['name' => 'Mr. Prakash Poojary', 'company' => 'Manorama Hotel', 'designation' => '', 'excerpt' => 'Taxlegal provides excellent service, putting their customers first and working hard to save money on annual taxes, going Beyond Bottom Line.', 'testimonial' => 'Taxlegal provides not only excellent service, but they put their customers first and work hard to save them money on their annual taxes, going Beyond Bottom Line.'],
            ['name' => 'Mr. Rohit Anand', 'company' => 'Raman Electricals', 'designation' => '', 'excerpt' => 'Adv Suresh Sharma and his team are extremely thorough, diligent and hard working. The work done by Taxlegal has always been first class.', 'testimonial' => 'Adv Suresh Sharma and his team are extremely thorough, diligent and hard working. They also take great care to understand the full picture of your tax situation which was crucial for us. The work done by Taxlegal and the team has always been first class. They are a very professional outfit and I would highly recommend them to others.'],
            ['name' => 'Mr. Akbar Pasha Pathan', 'company' => 'A.K. Tyre & Battery Services', 'designation' => '', 'excerpt' => 'Adv Suresh Sharma is a thorough professional and highly knowledgeable in dealing with complicated tax situations. Taxlegal truly took care of my taxes.', 'testimonial' => 'Adv Suresh Sharma , a thorough professional and highly knowledgeable in dealing with very complicated tax situations I would highly recommend their Tax Advisory services, and his organization Taxlegal truly took care of my personal taxes and now I have a peace of mind.'],
            ['name' => 'Mr. Zakir Mulani', 'company' => 'Almed Equipment', 'designation' => '', 'excerpt' => 'Their expertise helped us save a much greater amount of taxes absolutely by-the-book. Taxlegal always seemed to have my back.', 'testimonial' => 'Adv Suresh Sharma has always been known to us as an upright and forthcoming knowledgeable individual. Their expertise has helped us in saving a much greater amount of taxes than I could have imagined and absolutely by-the-book. Occasional issues that came up were handled very promptly and always with a good outcome. Taxlegal always seemed to "have my back".'],
            ['name' => 'Mr. Vikram Dave', 'company' => 'Rajdhani Steel', 'designation' => '', 'excerpt' => 'Their expertise uncovered significant flaws in my previous tax advisors\' approach, resulting in a large differential in refund due. Highly recommend their expert services.', 'testimonial' => 'Taxlegal, their expertise uncovered significant flaws in my previous tax advisors\' approach, resulting in a large differential in refund due. Taxlegal has looked out for my best tax interests and, combined with excellent responsiveness, hiring them was one of the wisest tax decisions I have made. Highly recommend them for the Great Results, Expert, Creative Services.'],
            ['name' => 'Mr. Dinesh Purohit', 'company' => 'Dhyanshi Industries Pvt Ltd', 'designation' => '', 'excerpt' => 'Adv Suresh Sharma is a reliable professional who delivers results in a useful and profitable outcome. I highly recommend his services.', 'testimonial' => 'Adv Suresh Sharma, is a professional, and reliable professional who delivers results in a useful and profitable outcome. I highly recommend his services.'],
            ['name' => 'Mr. Naresh Sharma', 'company' => 'Hansa Marine Service Pvt Ltd', 'designation' => '', 'excerpt' => 'Adv Suresh Sharma has proven to be an incredibly valuable asset in doing my taxes and advising on personal finances. He truly cares about his clients.', 'testimonial' => 'Adv. Suresh Sharma has proven to be an incredibly valuable asset to me when doing my taxes and advising me on managing my personal finances. From the first time I went to Adv Suresh, it was obvious that he\'s the type of professional who truly cares about his clients. And even more importantly, he has a good, practical, working knowledge of his field.'],
            ['name' => 'Mr. Vijay Rai', 'company' => 'V M Guardforce Pvt Ltd', 'designation' => '', 'excerpt' => 'Adv Suresh Sharma is an amazing advisor and consultant with excellent technical knowledge and in-depth experience, making clients understand even the most complex taxation.', 'testimonial' => 'I can honestly say that Adv Suresh Sharam is an amazing advisor and consultant with both an excellent technical knowledge and his indepth experiences with the ability, make clients understand even the most complex parts of the taxation.'],
            ['name' => 'Ms. Farhat Surti', 'company' => 'Adaa Boutique', 'designation' => '', 'excerpt' => 'Adv Suresh Sharma is highly respected, responsible and sincere in his work, along with a personal touch with his clients. I am indebted for all their services.', 'testimonial' => 'I know Adv Suresh Sharma, since I started my Adaa boutique. He is highly respected, responsible and sincere in his work, along with a personal touch with his clients. I am indebted to Sharma and company for all the services till date. My best wishes for his success.'],
            ['name' => 'Capt Razi Khan', 'company' => '', 'designation' => '', 'excerpt' => 'Mr Suresh Sharma and his team are highly professional and work with the highest level of honesty and integrity. They truly believe in customer satisfaction.', 'testimonial' => 'Mr Suresh Sharma and his team ,are highly professional and work with highest level of honesty and integrity. They truly believe in customer satisfaction ,and I am a testimony to this. I wish him and his team the very best in all his future endeavours!'],
            ['name' => 'NEC Infratech Pvt Ltd', 'company' => '', 'designation' => '', 'excerpt' => 'Accessible, responsive, professional and trustworthy. I highly recommend Taxlegal for their outstanding service and dedication.', 'testimonial' => 'Accessible, responsive, professional and trustworthy. I highly recommend.'],
            ['name' => 'Mr. Arvind Rahi', 'company' => 'Property Surge Pvt Ltd', 'designation' => '', 'excerpt' => 'Personalized and thorough service related to tax planning and filing. Very Responsive, Client Oriented, Expert Tax Consultant.', 'testimonial' => 'Personalized and thorough service related to tax planning and filling. Very Responsive, Client Oriented, Expert Tax Consultant.'],
            ['name' => 'Mr. M A Siddhiqui', 'company' => 'Rumana Transports Pvt Ltd', 'designation' => '', 'excerpt' => 'Fantastic service! They were easy to contact and got back to me quickly. I was very happy with the results, service, and cost.', 'testimonial' => 'Fantastic service! They were easy to contact and got back to me quickly. I was very happy with the results, service, and cost. I highly recommend them.'],
            ['name' => 'Mr. Ankit Patil', 'company' => 'Maxwise Home LLP', 'designation' => '', 'excerpt' => 'Taxlegal has helped me through a plethora of issues over the years. Adv Suresh gets back to me quickly with sensible advice and confidence.', 'testimonial' => 'Taxlegal and his team have helped me through a plethora issues over the years. Adv Suresh always gets back to me quickly with sensible advice, his experience gives me confidence, which is exactly what you want in the firm you turn to for advice. I highly recommend Taxlegal and their tax advisory services.'],
            ['name' => 'Mr. Sachin Purav', 'company' => 'Netra Properties Pvt Ltd', 'designation' => '', 'excerpt' => 'Highly Experienced, Professional, Reliable, Prompt. Taxlegal delivers outstanding consultancy and compliance services.', 'testimonial' => 'Highly Experienced, Professional, Reliable, Prompt.'],
            ['name' => 'Mr. Vinay Shrivastav', 'company' => 'Aayansh Shipping Service Pvt Ltd', 'designation' => '', 'excerpt' => 'Taxlegal, with its expertise in accounting and taxation, has been a wonderful investment for our business as our Business Consultant and Advisors.', 'testimonial' => 'Taxlegal, with its expertise in accounting and taxation, has been a wonderful investment for our business, having Taxlegal as our Business Consultant and Advisors.'],
            ['name' => 'Ms. Vyjanta Mistry', 'company' => 'Vish Citi Pvt Ltd', 'designation' => '', 'excerpt' => 'Taxlegal provided great advice and services that helped save a lot of money by optimizing our tax planning. Their vast knowledge has been enriching and helpful.', 'testimonial' => 'I and my husband we both have been struggling alot to find a tax advisory who can understand our business and help us scale up our business, not just filing of tax returns. We were planning to expand our business and were looking for loans. Everything was a big chaos, we had been so stress and were planning to give up . A slighted thing was shakening and scary, until we got connect with Adv Suresh Sharma. His firrm Taxlegal provided great advice and their services helped me save a lot of money by optimizing my tax planning by tax deductions. Adv Suresh was highly instrumental in negotiating with bankers for the loan purpose, preparing the finance reports, helping us clear the loan. His vast knowledge of 25 years has really been enriching and helpful for us. We found him a great family friend, the entire team;s approach is very professional, well organized. everything was done on time, his one on one review meeting, follow up phone calls has helped our business grow stronger with proper accounts and tax complainces, now we do not have any headace on this part as having Taxlegal as our advisor cum consultant, we find having a right partner with us walking throughoutt . I highly recommend'],
            ['name' => 'Mr. Ninad Sonawane', 'company' => 'ANS Continental Pvt Ltd', 'designation' => '', 'excerpt' => 'They go above and beyond to make sure we are always in compliance, making sure all forms are filed timely and accurately.', 'testimonial' => 'They go above and beyond to make sure we are in always in compliance, making sure all of the companies forms are filed timely and accurately, and they also diligently monitor and assess all accounts, statements and potential accounting issues. We would recommend Taxlegal to anyone looking for a responsive, trustworthy, thorough and personable team to help propel forward their small business.'],
            ['name' => 'Ms. Sonali Dhamanikar', 'company' => 'Eva Hospitality', 'designation' => '', 'excerpt' => 'I was amazed at his knowledge, and he was so patient with me, explaining everything clearly. You could not ask for a friendlier place to do business.', 'testimonial' => 'I used him the first time last year and was amazed at his knowledge, and he was so patient with me, and explained everything so I could understand it. You could not ask for a friendlier place to do business, and he is always available to us.I wish I had found him years ago I highly recommend Taxlegal and Adv Suresh services, should one look for acounting and tax advisory.'],
            ['name' => 'Mr. Santosh Sanap', 'company' => 'Pawan Carrier', 'designation' => '', 'excerpt' => 'Adv Suresh and his team found ways for me to lessen my tax burden. For almost 10 years, Taxlegal is still our trusted accounts and tax partner.', 'testimonial' => 'Adv Suresh and his team were able to find ways for me to lessen my tax burden. I was hooked there and then and it has been almost 10 yrs Taxlegal is still our accounts and tax consultant service partner. I could not have asked anything more having such a team of expertise as my advisor.'],
            ['name' => 'Mr. Prabjit Singh Chal', 'company' => 'Chal Transports', 'designation' => '', 'excerpt' => 'Taxlegal was the first accounting firm to develop a meaningful relationship and understanding of our family owned company. They continue to guide and strengthen us.', 'testimonial' => 'We have been struggling for the past 5 years to find the accounting firm that is right for our company. We are a family owned company and have certain needs and goals for our future. Taxlegal was the first accounting firm to develop a meaningful relationship and understanding of our company. With their 25 years of experience, they have provides the insight, expertise, and help we needed. Taxlegal already has and will continue to guide and strengthen our company for the coming years!'],
            ['name' => 'Mr. Rajratna Bhosle', 'company' => 'Multi Infrastructure Technologies Services', 'designation' => '', 'excerpt' => 'They provided great advice and services that helped save money by optimizing tax planning. Adv Suresh\'s vast knowledge of 25 years has helped our business grow stronger.', 'testimonial' => 'When my business got into expansion mode, I had to invest all my efforts and energies to the growing needs of my company. It was very important for me to have timely accounting tax planning and filling to be done in proper time. Here we always had a great support from Taxlegal. They provided great advice and their services helped me save a lot of money by optimizing my tax planning resulting to tax savings. Adv Suresh\'s vast knowledge of 25 years has really been enriching and helpful for us, Very professional, well organized. everything was done on time. His advices has helped my business grow stronger I highly recommend.'],
        ];

        foreach ($testimonials as $i => $t) {
            Testimonial::create(array_merge($t, [
                'rating' => 5,
                'photo' => null,
                'is_active' => true,
                'sort_order' => $i + 1,
            ]));
        }
    }
}
